creating array with numpy

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3])


In [5]:
print(arr)

[1 2 3]


In [6]:
print(type(arr))


<class 'numpy.ndarray'>


In [7]:
arr_0d = np.array(34)

In [8]:
print(arr_0d)

34


In [14]:
arr_2d = np.array([[2,3,4],[4,5,6]])

In [15]:
print(arr_2d)

[[2 3 4]
 [4 5 6]]


In [16]:
arr_3d = np.array([[[1,2,2],[2,3,4]],[[1,2,4],[3,4,4]]])

In [17]:
print(arr_3d)

[[[1 2 2]
  [2 3 4]]

 [[1 2 4]
  [3 4 4]]]
