In [1]:
import numpy as np

In [2]:
arr_1d = np.array([2,3,4,5])

In [3]:
print(arr_1d)

[2 3 4 5]


In [10]:
arr_2d = np.array([[1,2,3],[3,4,5]])

In [11]:
print(arr_2d)

[[1 2 3]
 [3 4 5]]


###list vs numpy array